### ISSUE TITLE
Previous page isn't displaying anything

### ISSUE THREAD

**Issue by moorepants** [thehackerwithin/davis#15]
See: http://www.thehackerwithin.org/davis/previous.html

**Comment by ixjlyons** [comment]
Would it be possible to dynamically handle separating previous/upcoming posts based on the date? That way you wouldn't have to modify the post category after each meeting.

**Comment by moorepants** [comment]
Yes, it should be possible. I'm not super familiar with Jekyll. But I've done similar things in other static generators. You should be able to alter the category based on some logic in the template, I think. Would have to look into it.
