### ISSUE TITLE
Hardcoded links to UW-Madison pages

### ISSUE THREAD

**Issue by ixjlyons** [thehackerwithin/davis#6]
The email and calendar icons in the side panel link to UW-Madison chapter pages. If we don't have analogous pages to link to, maybe those icons should just be removed. See [`_layout/layout.html`](https://github.com/thehackerwithin/davis/blob/9b575eb67752a9a180bb595fae9b1399c3d612f5/_layouts/layout.html#L50-#L51).

**Comment by moorepants** [comment]
Thanks. I'll fix them.

**Comment by moorepants** [comment]
Fixed.
